/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function LoliB({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/anime_loli.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.GLTF_created_0_rootJoint} />
          <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.material_3} skeleton={nodes.Object_10.skeleton} />
          <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.hair_shadow} skeleton={nodes.Object_11.skeleton} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.hair} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.material} skeleton={nodes.Object_8.skeleton} />
          <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.glasses} skeleton={nodes.Object_9.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/anime_loli.glb')
