/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Ninja1({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ninja.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RIGGING">
          <primitive object={nodes.spine} />
          <skinnedMesh name="BODY" geometry={nodes.BODY.geometry} material={materials.MergedBake_Baked} skeleton={nodes.BODY.skeleton} morphTargetDictionary={nodes.BODY.morphTargetDictionary} morphTargetInfluences={nodes.BODY.morphTargetInfluences} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ninja.glb')
