/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Room({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/room_japanes.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Cube015_Cube021.geometry} material={materials.stolik} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube014_Cube020.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube013_Cube019.geometry} material={materials['Material.005']} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube012_Cube018.geometry} material={materials['Material.005']} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube011_Cube017.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube003_Cube009.geometry} material={materials.stolik} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.pdloga_Cube005.geometry} material={materials.podloga} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.na_szybie_Plane002.geometry} material={materials['Material.002']} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.szyba_Plane001.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.okna_drewno_Cube004.geometry} material={materials['Material.002']} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.framuga_Cube003.geometry} material={materials['Material.002']} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.lewa_sciana_Cube002.geometry} material={materials['Material.003']} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.prawa_sciana_Cube001.geometry} material={materials['Material.007']} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.sciana_okno_Cube.geometry} material={materials.sciana_okno} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube015_Cube001.geometry} material={materials.stolik} position={[-15.58, -1.65, 26.94]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube014_Cube001.geometry} material={materials['Material.001']} position={[15.24, 0.55, 23.35]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube013_Cube001.geometry} material={materials['Material.005']} position={[15.24, 0.09, 23.35]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube012_Cube001.geometry} material={materials['Material.005']} position={[0, 0, 24.67]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube011_Cube001.geometry} material={materials['Material.001']} position={[0, 0, 24.67]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube003_Cube001.geometry} material={materials.stolik} position={[0, 0, 24.67]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.pdloga_Cube001.geometry} material={materials.podloga} position={[0, 0, 24.67]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.na_szybie_Plane001.geometry} material={materials['Material.002']} position={[0, 0, 49.25]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.szyba_Plane002.geometry} material={materials['Material.001']} position={[0, 0, 49.25]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.okna_drewno_Cube001.geometry} material={materials['Material.002']} position={[0, 0, 49.25]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.framuga_Cube001.geometry} material={materials['Material.002']} position={[0, 0, 49.25]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.lewa_sciana_Cube001.geometry} material={materials['Material.003']} position={[0, 0, 24.67]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.prawa_sciana_Cube002.geometry} material={materials['Material.007']} position={[0, 0, 24.67]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.sciana_okno_Cube001.geometry} material={materials.sciana_okno} position={[0, 0, 49.25]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube015_Cube002.geometry} material={materials.stolik} position={[-17.62, 9.88, 14.32]} rotation={[-Math.PI, -Math.PI / 2, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube003_Cube002.geometry} material={materials.stolik} position={[17.2, 10.22, 13.55]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.lewa_sciana_Cube003.geometry} material={materials['Material.003']} position={[-0.47, 24.11, 1.45]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.35, 1, 1.49]} />
      <mesh geometry={nodes.lewa_sciana_Cube004.geometry} material={materials['Material.003']} position={[-0.47, 24.11, 26.11]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[1.35, 1, 1.49]} />
      <mesh geometry={nodes.Cube014_Cube002.geometry} material={materials['Material.001']} position={[15.01, 13.76, 13.65]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[1.35, 1, 1]} />
      <mesh geometry={nodes.Cube013_Cube002.geometry} material={materials['Material.005']} position={[15.47, 13.76, 13.65]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={[1.35, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/room_japanes.glb')
