/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ae86({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scuffed_ae86.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes._9_001_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
            <mesh geometry={nodes._9_001_levin_headlights_0.geometry} material={materials.levin_headlights} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Airfilter_Corolla_engine_corolla_0.geometry} material={materials.engine_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Alternator_Corolla_engine_corolla_0.geometry} material={materials.engine_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Ansaugbr��cke2_Corolla_Aluminum_Corolla_0'].geometry} material={materials.Aluminum_Corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['Ansaugbr��cke_Corolla_engine_corolla_0'].geometry} material={materials.engine_corolla} />
          </group>
          <group position={[0, -0.29, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Badge_Corolla_chrome_0.geometry} material={materials.chrome} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Belt1_Corolla_rubber_0.geometry} material={materials.rubber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Belt2_Corolla_rubber_0.geometry} material={materials.rubber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Belt3_Corolla_rubber_0.geometry} material={materials.rubber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Belt4_Corolla_Aluminum_Corolla_0.geometry} material={materials.Aluminum_Corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.bl_buttons_bl_0.geometry} material={materials.buttons_bl} />
          </group>
          <group position={[-37.87, 61.59, 85.34]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Brakepedal_Corolla_Aluminum_black_0.geometry} material={materials['Aluminum_black.001']} />
            <mesh geometry={nodes.Brakepedal_Corolla_pedals_0.geometry} material={materials['trunk.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Bumper_rear_Corolla_black_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
            <mesh geometry={nodes.Bumper_rear_Corolla_black_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Buttons_Corolla_buttons_0.geometry} material={materials.buttons} />
            <mesh geometry={nodes.Buttons_Corolla_controlpanel_0.geometry} material={materials.controlpanel} />
            <mesh geometry={nodes.Buttons_Corolla_leuchte_0.geometry} material={materials.leuchte} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Buttons_Corolla_bl_buttons_bl_0.geometry} material={materials.buttons_bl} />
            <mesh geometry={nodes.Buttons_Corolla_bl_controlpanel_0.geometry} material={materials.controlpanel} />
            <mesh geometry={nodes.Buttons_Corolla_bl_leuchte_bl_0.geometry} material={materials.leuchte_bl} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Chassis_Corolla_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
            <mesh geometry={nodes.Chassis_Corolla_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Chassis_Corolla_blackbump_0.geometry} material={materials.blackbump} />
            <mesh geometry={nodes.Chassis_Corolla_boot__spec__0.geometry} material={materials.boot__spec} />
            <mesh geometry={nodes.Chassis_Corolla_etki_0.geometry} material={materials.etki} />
            <mesh geometry={nodes.Chassis_Corolla_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
            <mesh geometry={nodes.Chassis_Corolla_plastic_corolla_0.geometry} material={materials.plastic_corolla} />
            <mesh geometry={nodes.Chassis_Corolla_rubber_0.geometry} material={materials.rubber} />
            <mesh geometry={nodes.Chassis_Corolla_seats__spec__0.geometry} material={materials.broken__spec} />
            <mesh geometry={nodes.Chassis_Corolla_trunk_0.geometry} material={materials.trunk} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Chassis_Corolla_eb_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Chassis_Corolla_eb_blackbump_0.geometry} material={materials.blackbump} />
            <mesh geometry={nodes.Chassis_Corolla_eb_engine_corolla_0.geometry} material={materials.engine_corolla} />
            <mesh geometry={nodes.Chassis_Corolla_eb_etki_0.geometry} material={materials.etki} />
            <mesh geometry={nodes.Chassis_Corolla_eb_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
            <mesh geometry={nodes.Chassis_Corolla_eb_plastic_corolla_0.geometry} material={materials.plastic_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Chassis_Corolla_eb_2_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Chassis_Corolla_eb_2_blackbump_0.geometry} material={materials.blackbump} />
            <mesh geometry={nodes.Chassis_Corolla_eb_2_etki_0.geometry} material={materials.etki} />
            <mesh geometry={nodes.Chassis_Corolla_eb_2_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
            <mesh geometry={nodes.Chassis_Corolla_eb_2_rubber_0.geometry} material={materials.rubber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Clock_YotaDigiClock_0.geometry} material={materials.YotaDigiClock} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Clock_bl_YotaDigiClock_bl_0.geometry} material={materials.YotaDigiClock_bl} />
          </group>
          <group position={[-25.89, 61.6, 85.25]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Clutchpedal_Corolla_Aluminum_black_0.geometry} material={materials['Aluminum_black.001']} />
            <mesh geometry={nodes.Clutchpedal_Corolla_pedals_0.geometry} material={materials['trunk.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Coilover_F_Corolla_engine_corolla_0.geometry} material={materials['engine_corolla.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Coilover_F_Corolla_race_engine_corolla_0.geometry} material={materials['engine_corolla.001']} />
            <mesh geometry={nodes.Coilover_F_Corolla_race_engine_wires_0.geometry} material={materials['engine_wires.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Coilover_R_Corolla_engine_corolla2_0.geometry} material={materials['trunk.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Coilover_R_Corolla_race_engine_corolla2_0.geometry} material={materials['trunk.001']} />
            <mesh geometry={nodes.Coilover_R_Corolla_race_engine_wires_0.geometry} material={materials['engine_wires.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Coolant_Corolla_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Coolantriffles_Corolla_engine_corolla_0.geometry} material={materials.engine_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brake_F_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brake_R_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brake_race_F_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brake_race_R_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brakedisc_4l_FL_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brakedisc_4l_FR_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brakedisc_4l_RL_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brakedisc_4l_RR_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brakedisc_FL_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brakedisc_FR_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brakedisc_race_FL_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brakedisc_race_FR_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brakedisc_race_RL_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group position={[0, 0, -2.96]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-100}>
            <mesh geometry={nodes.coupe_brakedisc_race_RL001_coupe001_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brakedisc_race_RR_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group position={[0, 0, -2.96]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-100}>
            <mesh geometry={nodes.coupe_brakedisc_race_RR001_coupe001_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brakedisc_RL_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_brakedisc_RR_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.coupe_strut_bar_chrome_0.geometry} material={materials.chrome} />
            <mesh geometry={nodes.coupe_strut_bar_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group position={[-79.7, 75.35, -32.24]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-79.37, 77.43, 24.51]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve001_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-78.95, 80.05, 1.24]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve002_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-79.05, 79.43, 12.17]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve003_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-79.86, 74.36, -19.9]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve004_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-79.64, 75.74, -8.08]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve005_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-79.89, 74.17, 27.1]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve006_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-79.84, 74.45, 1.16]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve007_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-80.1, 72.87, 12.02]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve008_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-79.97, 73.66, 16.46]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve009_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-80.06, 73.07, 37]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve010_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-80.07, 73.03, 42.42]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve011_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-80.15, 72.51, 33.32]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve012_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-80.03, 73.26, 48.15]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve013_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-80.08, 72.96, 52.08]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve014_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-80.15, 72.55, 9.05]} rotation={[-Math.PI / 2, -1.41, -Math.PI / 2]} scale={1998.01}>
            <mesh geometry={nodes.Curve015_SVGMat001_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-39.73, 88.64, -206.24]} rotation={[-2.67, -0.06, -3.13]} scale={845.26}>
            <mesh geometry={nodes.Curve016_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-44.19, 87.55, -206.42]} rotation={[-2.64, -0.06, -3.12]} scale={845.26}>
            <mesh geometry={nodes.Curve017_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-43.9, 88.86, -205.7]} rotation={[-2.63, -0.07, -3.07]} scale={845.26}>
            <mesh geometry={nodes.Curve018_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-48.27, 88.25, -205.62]} rotation={[-2.67, -0.09, 3.14]} scale={845.26}>
            <mesh geometry={nodes.Curve019_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-52.9, 87.77, -205.4]} rotation={[-2.68, -0.11, -3.13]} scale={845.26}>
            <mesh geometry={nodes.Curve020_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-56.8, 87.59, -205.02]} rotation={[-2.7, -0.13, -3.12]} scale={845.26}>
            <mesh geometry={nodes.Curve021_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-61.27, 87.39, -204.25]} rotation={[-2.69, -0.2, -3.09]} scale={845.26}>
            <mesh geometry={nodes.Curve022_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-61.32, 87.36, -204.32]} rotation={[-2.69, -0.17, -3.1]} scale={845.26}>
            <mesh geometry={nodes.Curve023_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-81.06, 53.7, -84.99]} rotation={[-Math.PI, -1.57, 0]} scale={-1086.85}>
            <mesh geometry={nodes.Curve043_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-81.06, 53.14, -82.22]} rotation={[-Math.PI, -1.57, 0]} scale={-1086.85}>
            <mesh geometry={nodes.Curve044_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-81.06, 53.78, -82.27]} rotation={[-Math.PI, -1.57, 0]} scale={-1086.85}>
            <mesh geometry={nodes.Curve045_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-81.06, 53.46, -79.47]} rotation={[-Math.PI, -1.57, 0]} scale={-1086.85}>
            <mesh geometry={nodes.Curve046_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-81.06, 53.36, -76.54]} rotation={[-Math.PI, -1.57, 0]} scale={-1086.85}>
            <mesh geometry={nodes.Curve047_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-81.06, 53.48, -73.91]} rotation={[-Math.PI, -1.57, 0]} scale={-1086.85}>
            <mesh geometry={nodes.Curve048_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-81.06, 53.38, -71]} rotation={[-Math.PI, -1.57, 0]} scale={-1086.85}>
            <mesh geometry={nodes.Curve049_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[-81.06, 53.34, -71.04]} rotation={[-Math.PI, -1.57, 0]} scale={-1086.85}>
            <mesh geometry={nodes.Curve050_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[80.9, 53.68, -69.84]} rotation={[0, 1.57, 0]} scale={1116.1}>
            <mesh geometry={nodes.Curve051_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[80.9, 53.19, -72.64]} rotation={[0, 1.57, 0]} scale={1116.1}>
            <mesh geometry={nodes.Curve052_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[80.9, 53.77, -72.64]} rotation={[0, 1.57, 0]} scale={1116.1}>
            <mesh geometry={nodes.Curve053_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[80.9, 53.43, -75.52]} rotation={[0, 1.57, 0]} scale={1116.1}>
            <mesh geometry={nodes.Curve054_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[80.9, 53.33, -78.51]} rotation={[0, 1.57, 0]} scale={1116.1}>
            <mesh geometry={nodes.Curve055_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[80.9, 53.45, -81.2]} rotation={[0, 1.57, 0]} scale={1116.1}>
            <mesh geometry={nodes.Curve056_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[80.9, 53.35, -84.2]} rotation={[0, 1.57, 0]} scale={1116.1}>
            <mesh geometry={nodes.Curve057_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[80.9, 53.44, -84.15]} rotation={[0, 1.57, 0]} scale={1116.1}>
            <mesh geometry={nodes.Curve058_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[55.14, 87.02, -205.63]} rotation={[-2.73, 0.07, -0.04]} scale={-857.25}>
            <mesh geometry={nodes.Curve059_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[50.32, 87.54, -205.79]} rotation={[-2.73, 0.07, -0.04]} scale={-857.25}>
            <mesh geometry={nodes.Curve060_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[45.48, 87.43, -206.23]} rotation={[-2.69, 0.07, -0.04]} scale={-857.25}>
            <mesh geometry={nodes.Curve061_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[40.35, 87.29, -206.8]} rotation={[-2.73, 0.07, -0.04]} scale={-857.25}>
            <mesh geometry={nodes.Curve062_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[33.9, 86.82, -207.43]} rotation={[-2.73, 0.07, -0.04]} scale={-857.25}>
            <mesh geometry={nodes.Curve063_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[30.11, 86.62, -207.68]} rotation={[-2.73, 0.07, -0.04]} scale={-857.25}>
            <mesh geometry={nodes.Curve064_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[28.15, 86.58, -207.83]} rotation={[-2.73, 0.06, -0.04]} scale={-857.25}>
            <mesh geometry={nodes.Curve065_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[24.48, 86.63, -207.92]} rotation={[-2.73, 0.03, -0.03]} scale={-857.25}>
            <mesh geometry={nodes.Curve066_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[19.92, 86.42, -208.2]} rotation={[-2.73, 0.03, -0.03]} scale={-857.25}>
            <mesh geometry={nodes.Curve067_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[15.22, 86.26, -208.45]} rotation={[-2.73, 0.07, -0.04]} scale={-857.25}>
            <mesh geometry={nodes.Curve068_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[13.42, 86.54, -208.34]} rotation={[-2.73, 0.07, -0.04]} scale={-857.25}>
            <mesh geometry={nodes.Curve069_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group position={[44.86, 87.32, -206.33]} rotation={[-2.73, 0.07, -0.04]} scale={-857.25}>
            <mesh geometry={nodes.Curve070_SVGMat002_0.geometry} material={materials['SVGMat.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Dashboard_Corolla_buttons_0.geometry} material={materials.buttons} />
            <mesh geometry={nodes.Dashboard_Corolla_chrome_0.geometry} material={materials['chrome.001']} />
            <mesh geometry={nodes.Dashboard_Corolla_controlpanel_0.geometry} material={materials.controlpanel} />
            <mesh geometry={nodes.Dashboard_Corolla_dark_0.geometry} material={materials.dark} />
            <mesh geometry={nodes.Dashboard_Corolla_leuchte_0.geometry} material={materials.leuchte} />
            <mesh geometry={nodes.Dashboard_Corolla_ok_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Dashboard_Corolla_plastic_corolla2_0.geometry} material={materials['plastic_corolla2.001']} />
            <mesh geometry={nodes.Dashboard_Corolla_plastic_corolla_0.geometry} material={materials['plastic_corolla.001']} />
            <mesh geometry={nodes.Dashboard_Corolla_poop_0.geometry} material={materials.poop} />
            <mesh geometry={nodes.Dashboard_Corolla_rest_0.geometry} material={materials['Material.003']} />
            <mesh geometry={nodes.Dashboard_Corolla_Signal_L_0.geometry} material={materials.Signal_L} />
            <mesh geometry={nodes.Dashboard_Corolla_Signal_R_0.geometry} material={materials.Signal_R} />
            <mesh geometry={nodes.Dashboard_Corolla_softtouch2_0.geometry} material={materials.softtouch2} />
            <mesh geometry={nodes.Dashboard_Corolla_softtouch_0.geometry} material={materials.softtouch} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Differential_Corolla_underchassis_corolla_0.geometry} material={materials.trunk} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Door_int_L_Corolla_chrome_0.geometry} material={materials['chrome.001']} />
            <mesh geometry={nodes.Door_int_L_Corolla_leather_corolla_0.geometry} material={materials['trunk.001']} />
            <mesh geometry={nodes.Door_int_L_Corolla_softtouch2_0.geometry} material={materials.softtouch2} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Door_int_R_Corolla_chrome_0.geometry} material={materials['chrome.001']} />
            <mesh geometry={nodes.Door_int_R_Corolla_leather_corolla_0.geometry} material={materials['trunk.001']} />
            <mesh geometry={nodes.Door_int_R_Corolla_softtouch2_0.geometry} material={materials.softtouch2} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Door_L_Corolla_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Door_L_Corolla_blackbump_0.geometry} material={materials.blackbump} />
            <mesh geometry={nodes.Door_L_Corolla_chrome_0.geometry} material={materials.chrome} />
            <mesh geometry={nodes.Door_L_Corolla_etki_0.geometry} material={materials.etki} />
            <mesh geometry={nodes.Door_L_Corolla_interior__spec__0.geometry} material={materials.interior__spec} />
            <mesh geometry={nodes.Door_L_Corolla_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
            <mesh geometry={nodes.Door_L_Corolla_plastic_corolla_0.geometry} material={materials.plastic_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Door_R_Corolla_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Door_R_Corolla_blackbump_0.geometry} material={materials.blackbump} />
            <mesh geometry={nodes.Door_R_Corolla_chrome_0.geometry} material={materials.chrome} />
            <mesh geometry={nodes.Door_R_Corolla_etki_0.geometry} material={materials.etki} />
            <mesh geometry={nodes.Door_R_Corolla_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
            <mesh geometry={nodes.Door_R_Corolla_plastic_corolla_0.geometry} material={materials.plastic_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.EngineBlock2_Corolla_Aluminum_Corolla_0.geometry} material={materials.Aluminum_Corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.EngineBlock3_Corolla_engine_corolla_0.geometry} material={materials.engine_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.EngineBlock4_Corolla_plastic_corolla2_0.geometry} material={materials.plastic_corolla2} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.EngineBlock_Corolla_engine_corolla_0.geometry} material={materials.engine_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.engineholder_Corolla_engine_corolla_0.geometry} material={materials['engine_corolla.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.EngineLabel2_Corolla_blue_0.geometry} material={materials.blue} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.EngineLabel_Corolla_Aluminum_Corolla_0.geometry} material={materials.Aluminum_Corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Exhaust_Corolla_engine_corolla2_0.geometry} material={materials.trunk} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Fender_L_Corolla_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Fender_L_Corolla_blackbump_0.geometry} material={materials.blackbump} />
            <mesh geometry={nodes.Fender_L_Corolla_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Fender_R_Corolla_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Fender_R_Corolla_blackbump_0.geometry} material={materials.blackbump} />
            <mesh geometry={nodes.Fender_R_Corolla_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group position={[60.12, 35.56, 118.98]} rotation={[0, 1.57, 0]} scale={[11.45, 11.45, 10.68]}>
            <mesh geometry={nodes.FL_Caliper_BrakeCaliper_0.geometry} material={materials.BrakeCaliper} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Floor_Corolla_underchassis_corolla_0.geometry} material={materials['trunk.001']} />
          </group>
          <group position={[-60.46, 35.56, 118.97]} rotation={[Math.PI, 1.57, 0]} scale={[-11.45, -11.45, -10.68]}>
            <mesh geometry={nodes.FR_Caliper_BrakeCaliper_0.geometry} material={materials.BrakeCaliper} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Front_Bumper_Corolla_blackbump_0.geometry} material={materials.blackbump} />
            <mesh geometry={nodes.Front_Bumper_Corolla_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Front_Bumper_Corolla_black_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
            <mesh geometry={nodes.Front_Bumper_Corolla_black_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Fuelfilter_Corolla_engine_corolla_0.geometry} material={materials.engine_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Gasket_Corolla_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
          </group>
          <group position={[-50.34, 67.33, 91.16]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Gaspedal_Corolla_Aluminum_black_0.geometry} material={materials['Aluminum_black.001']} />
            <mesh geometry={nodes.Gaspedal_Corolla_pedals_0.geometry} material={materials['trunk.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Gauge_temp_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
            <mesh geometry={nodes.Gauge_temp_glass_gauges_0.geometry} material={materials.glass_gauges} />
            <mesh geometry={nodes.Gauge_temp_plastic_corolla_0.geometry} material={materials.plastic_corolla} />
            <mesh geometry={nodes.Gauge_temp_watertemperature_0.geometry} material={materials.watertemperature} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Gauge_Turbo_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
            <mesh geometry={nodes.Gauge_Turbo_glass_gauges_0.geometry} material={materials.glass_gauges} />
            <mesh geometry={nodes.Gauge_Turbo_plastic_corolla_0.geometry} material={materials.plastic_corolla} />
            <mesh geometry={nodes.Gauge_Turbo_turbo_pressure_0.geometry} material={materials.turbo_pressure} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Glass_FL_Corolla_int_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Glass_FL_Corolla_int_glass_corolla_int_0.geometry} material={materials.glass_corolla_int} />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={-100}>
            <mesh geometry={nodes.Glass_FL_Corolla_int001_black001_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Glass_FL_Corolla_int001_glass_corolla_int001_0.geometry} material={materials.glass_corolla_int} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Glass_R_Corolla_int_glass_corolla_int_0.geometry} material={materials.glass_corolla_int} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Glass_RL_Corolla_int_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Glass_RL_Corolla_int_glass_corolla_int_0.geometry} material={materials.glass_corolla_int} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Glass_RR_Corolla_int_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Glass_RR_Corolla_int_glass_corolla_int_0.geometry} material={materials.glass_corolla_int} />
          </group>
          <group position={[2.36, 48.87, -19.11]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Handbrake_Corolla_Aluminum_black_0.geometry} material={materials['Aluminum_black.001']} />
            <mesh geometry={nodes.Handbrake_Corolla_rubber_0.geometry} material={materials['rubber.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Head1_Corolla_engine_corolla_0.geometry} material={materials.engine_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Head2_Corolla_engine_corolla_0.geometry} material={materials.engine_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Headglasslight_FR_Corolla_headlight_0.geometry} material={materials.headlight} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Headlight_FL_Corolla_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
            <mesh geometry={nodes.Headlight_FL_Corolla_blackbump_0.geometry} material={materials.blackbump} />
            <mesh geometry={nodes.Headlight_FL_Corolla_Material003_0.geometry} material={materials['Material.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Headlight_FR_Corolla_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
            <mesh geometry={nodes.Headlight_FR_Corolla_Material002_0.geometry} material={materials['Material.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Headlightglass_FL_Corolla_headlight_0.geometry} material={materials.headlight} />
          </group>
          <group position={[-53.71, 86.2, 40.32]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Headlightswitch_leuchte_0.geometry} material={materials.leuchte} />
          </group>
          <group position={[-53.71, 86.2, 40.32]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Headlightswitch_bl_leuchte_bl_0.geometry} material={materials.leuchte_bl} />
          </group>
          <group position={[-53.71, 86.2, 40.32]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.headlightswitch_Corolla_plastic_corolla2_0.geometry} material={materials['plastic_corolla2.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Headliner_Corolla_carpet_corolla_0.geometry} material={materials.carpet_corolla} />
            <mesh geometry={nodes.Headliner_Corolla_chrome_0.geometry} material={materials['chrome.001']} />
            <mesh geometry={nodes.Headliner_Corolla_hatch_0.geometry} material={materials['glass_gauges.001']} />
            <mesh geometry={nodes.Headliner_Corolla_makeitblack_0.geometry} material={materials.makeitblack} />
            <mesh geometry={nodes.Headliner_Corolla_plastic_corolla_0.geometry} material={materials['plastic_corolla.001']} />
            <mesh geometry={nodes.Headliner_Corolla_reverselight_corolla_0.geometry} material={materials['trunk.001']} />
            <mesh geometry={nodes.Headliner_Corolla_rubber_0.geometry} material={materials['rubber.001']} />
            <mesh geometry={nodes.Headliner_Corolla_softtouch_0.geometry} material={materials.softtouch} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Hood_Corolla_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} position={[0, -1.13, -0.22]} rotation={[-0.99, 0, 0]} />
            <mesh geometry={nodes.Hood_Corolla_Material001_0.geometry} material={materials['Material.001']} position={[0, -1.13, -0.22]} rotation={[-0.99, 0, 0]} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Hub_Corolla_engine_corolla_0.geometry} material={materials['engine_corolla.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Hutablage_Corolla_etki_intcarpet_0.geometry} material={materials.etki_intcarpet} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Int_Mirror_Corolla_leather_corolla_0.geometry} material={materials['trunk.001']} />
          </group>
          <group position={[-0.01, 33.47, -38.71]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Kadanwelle_Corolla_engine_corolla2_0.geometry} material={materials.trunk} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.kouki_garnish_tr_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
            <mesh geometry={nodes.kouki_garnish_tr_blackbump_0.geometry} material={materials.blackbump} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Left_tl_corolla_signal_l_0.geometry} material={materials.corolla_signal_l} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.left_tl2_headlight_0.geometry} material={materials.headlight} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.lollo_buttons_0.geometry} material={materials.buttons} />
            <mesh geometry={nodes.lollo_leather_corolla_0.geometry} material={materials['trunk.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Lowerarm_Corolla_engine_corolla_0.geometry} material={materials['engine_corolla.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Manual_Transmission_Corolla_engine_corolla2_0.geometry} material={materials.trunk} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Mirror_L_Corolla_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Mirror_L_Corolla_Matte__FF808080__env_12_spec__0.geometry} material={materials.Matte__FF808080__env_12_spec} />
            <mesh geometry={nodes.Mirror_L_Corolla_reflection_0.geometry} material={materials.trunk} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Mirror_L_Corolla_painted_Matte__FF808080__env_12_spec__0.geometry} material={materials.Matte__FF808080__env_12_spec} />
            <mesh geometry={nodes.Mirror_L_Corolla_painted_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
            <mesh geometry={nodes.Mirror_L_Corolla_painted_reflection_0.geometry} material={materials.trunk} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Mirror_R_Corolla_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Mirror_R_Corolla_Matte__FF808080__env_12_spec__0.geometry} material={materials.Matte__FF808080__env_12_spec} />
            <mesh geometry={nodes.Mirror_R_Corolla_reflection_0.geometry} material={materials.trunk} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Mirror_R_Corolla_painted_Matte__FF808080__env_12_spec__0.geometry} material={materials.Matte__FF808080__env_12_spec} />
            <mesh geometry={nodes.Mirror_R_Corolla_painted_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
            <mesh geometry={nodes.Mirror_R_Corolla_painted_reflection_0.geometry} material={materials.trunk} />
          </group>
          <group position={[-18.68, 85.06, 53.3]} rotation={[Math.PI, 0, 0]} scale={100}>
            <mesh geometry={nodes.Needle1_Corolla_leuchte_0.geometry} material={materials.leuchte} />
          </group>
          <group position={[-18.68, 85.06, 53.3]} rotation={[Math.PI, 0, 0]} scale={100}>
            <mesh geometry={nodes.Needle1_Corolla_bl_leuchte_bl_0.geometry} material={materials.leuchte_bl} />
          </group>
          <group position={[-26.23, 87.35, 52.82]} rotation={[Math.PI, 0, 0]} scale={100}>
            <mesh geometry={nodes.Needle2_Corolla_leuchte_0.geometry} material={materials.leuchte} />
            <mesh geometry={nodes.Needle2_Corolla_plastic_corolla_0.geometry} material={materials['plastic_corolla.001']} />
          </group>
          <group position={[-26.23, 87.35, 52.82]} rotation={[Math.PI, 0, 0]} scale={100}>
            <mesh geometry={nodes.Needle2_Corolla_bl_leuchte_bl_0.geometry} material={materials.leuchte_bl} />
            <mesh geometry={nodes.Needle2_Corolla_bl_plastic_corolla_0.geometry} material={materials['plastic_corolla.001']} />
          </group>
          <group position={[-36.99, 87.11, 52.84]} rotation={[Math.PI, 0, 0]} scale={100}>
            <mesh geometry={nodes.Needle3_Corolla_leuchte_0.geometry} material={materials.leuchte} />
            <mesh geometry={nodes.Needle3_Corolla_plastic_corolla_0.geometry} material={materials['plastic_corolla.001']} />
          </group>
          <group position={[-36.99, 87.11, 52.84]} rotation={[Math.PI, 0, 0]} scale={100}>
            <mesh geometry={nodes.Needle3_Corolla_bl_leuchte_bl_0.geometry} material={materials.leuchte_bl} />
            <mesh geometry={nodes.Needle3_Corolla_bl_plastic_corolla_0.geometry} material={materials['plastic_corolla.001']} />
          </group>
          <group position={[-41.18, 84.91, 53.16]} rotation={[Math.PI, 0, 0]} scale={100}>
            <mesh geometry={nodes.Needle4_Corolla_leuchte_0.geometry} material={materials.leuchte} />
          </group>
          <group position={[-41.18, 84.91, 53.16]} rotation={[Math.PI, 0, 0]} scale={100}>
            <mesh geometry={nodes.Needle4_Corolla_bl_leuchte_bl_0.geometry} material={materials.leuchte_bl} />
          </group>
          <group position={[-44.89, 84.91, 53.16]} rotation={[-Math.PI, 0, 1.05]} scale={100}>
            <mesh geometry={nodes.Needle5_Corolla_leuchte_0.geometry} material={materials.leuchte} />
          </group>
          <group position={[-44.89, 84.91, 53.16]} rotation={[-Math.PI, 0, 1.05]} scale={100}>
            <mesh geometry={nodes.Needle5_Corolla_bl_leuchte_bl_0.geometry} material={materials.leuchte_bl} />
          </group>
          <group position={[-2.51, 87.44, 41.89]} rotation={[-3, 0, 0]} scale={100}>
            <mesh geometry={nodes.Needle_tempi_leuchte_0.geometry} material={materials.leuchte} />
            <mesh geometry={nodes.Needle_tempi_plastic_corolla_0.geometry} material={materials['plastic_corolla.001']} />
          </group>
          <group position={[-2.64, 94.61, 43.85]} rotation={[-3, 0, 0]} scale={100}>
            <mesh geometry={nodes.Needle_turbo_leuchte_0.geometry} material={materials.leuchte} />
            <mesh geometry={nodes.Needle_turbo_plastic_corolla_0.geometry} material={materials['plastic_corolla.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Oilpan2_Corolla_Aluminum_Corolla_0.geometry} material={materials.Aluminum_Corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Oilpan_Corolla_engine_corolla_0.geometry} material={materials.engine_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Pipe1_Corolla_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Pipe2_Corolla_coupe_0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
            <mesh geometry={nodes.Pipe2_Corolla_rubber_0.geometry} material={materials.rubber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.PowerSteeringPump_Corolla_engine_corolla_0.geometry} material={materials.engine_corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Protection_Corolla_plastic_corolla_0.geometry} material={materials.plastic_corolla} />
          </group>
          <group position={[15.32, 53.76, 152.46]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Pully1_Corolla_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
          </group>
          <group position={[-7.3, 51.13, 149.87]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Pully2_Corolla_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
          </group>
          <group position={[-0.99, 33.14, 150.52]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Pully3_Corolla_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
          </group>
          <group position={[-15.35, 37.94, 149.62]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Pully4_Corolla_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
          </group>
          <group position={[6.29, 70.05, 146.08]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Pully5_Corolla_pruple_0.geometry} material={materials.pruple} />
          </group>
          <group position={[-5.86, 70.05, 146.05]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Pully6_Corolla_pruple_0.geometry} material={materials.pruple} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.racingseat_driver_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
            <mesh geometry={nodes.racingseat_driver_Aluminum_Corolla_0.geometry} material={materials.Aluminum_Corolla} />
            <mesh geometry={nodes.racingseat_driver_carero_0.geometry} material={materials.glass_gauges} />
            <mesh geometry={nodes.racingseat_driver_Racingseats_0.geometry} material={materials.Racingseats} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Rear_Doorcard_seats_corolla_0.geometry} material={materials.trunk} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Rear_Doorcard_beige_seats_corolla_beige_0.geometry} material={materials['seats_corolla_beige.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Rear_Doorcard_blue_seats_corolla_blue_0.geometry} material={materials.glass_gauges} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Rear_Doorcard_red_seats_corolla_red_purple_0.geometry} material={materials.glass_gauges} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Rear_Doorcard_redder_seats_corolla_red_0.geometry} material={materials.glass_gauges} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Redstripe_Corolla_early_strip_early_0.geometry} material={materials.glass_gauges} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Right_tl_corolla_signal_r_0.geometry} material={materials.corolla_signal_r} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Right_tl2_headlight_0.geometry} material={materials.headlight} />
          </group>
          <group position={[60.12, 35.56, -122.04]} rotation={[0, 1.57, 0]} scale={[11.45, 11.45, 10.68]}>
            <mesh geometry={nodes.RL_Caliper_BrakeCaliper_0.geometry} material={materials.BrakeCaliper} />
          </group>
          <group position={[69.26, 35.56, -122.04]} rotation={[-Math.PI / 2, 0, 0]} scale={[97.87, 91.92, 91.92]}>
            <mesh geometry={nodes.RL_Wheel_Brake_Disc_0.geometry} material={materials['Brake_Disc.001']} />
            <mesh geometry={nodes.RL_Wheel_RimMaterial_0.geometry} material={materials.TireMaterial} />
            <mesh geometry={nodes.RL_Wheel_TireMaterial_0.geometry} material={materials.TireMaterial} />
          </group>
          <group position={[69.26, 35.56, 119.08]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-97.87, -91.92, -91.92]}>
            <mesh geometry={nodes.RL_Wheel001_Brake_Disc001_0.geometry} material={materials['Brake_Disc.001']} />
            <mesh geometry={nodes.RL_Wheel001_RimMaterial001_0.geometry} material={materials.TireMaterial} />
            <mesh geometry={nodes.RL_Wheel001_TireMaterial001_0.geometry} material={materials.TireMaterial} />
          </group>
          <group position={[-60.46, 35.56, -122.04]} rotation={[Math.PI, 1.57, 0]} scale={[-11.45, -11.45, -10.68]}>
            <mesh geometry={nodes.RR_Caliper_BrakeCaliper_0.geometry} material={materials.BrakeCaliper} />
          </group>
          <group position={[-69.61, 35.56, -122.04]} rotation={[-Math.PI / 2, 0, 0]} scale={[97.87, 91.92, 91.92]}>
            <mesh geometry={nodes.RR_Wheel_Brake_Disc_0.geometry} material={materials['Brake_Disc.001']} />
            <mesh geometry={nodes.RR_Wheel_RimMaterial_0.geometry} material={materials.TireMaterial} />
            <mesh geometry={nodes.RR_Wheel_TireMaterial_0.geometry} material={materials.TireMaterial} />
          </group>
          <group position={[-69.61, 35.56, 119.08]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-97.87, -91.92, -91.92]}>
            <mesh geometry={nodes.RR_Wheel001_Brake_Disc001_0.geometry} material={materials['Brake_Disc.001']} />
            <mesh geometry={nodes.RR_Wheel001_RimMaterial001_0.geometry} material={materials.TireMaterial} />
            <mesh geometry={nodes.RR_Wheel001_TireMaterial001_0.geometry} material={materials.TireMaterial} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.rubberthing_levin_rubber_0.geometry} material={materials.rubber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Screws1_Corolla_Aluminum_Corolla_0.geometry} material={materials.Aluminum_Corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Screws2_Corolla_Aluminum_Corolla_0.geometry} material={materials.Aluminum_Corolla} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.scx1_headlight_0.geometry} material={materials.headlight} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.scx2_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.scx3_black_0.geometry} material={materials.black} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Seats_R_Corolla_seats_corolla_0.geometry} material={materials['trunk.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Seats_R_Corolla_beiger_seats_corolla_beige_0.geometry} material={materials.seats_corolla_beige} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Seats_R_Corolla_blue_seats_corolla_blue_0.geometry} material={materials['glass_gauges.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Seats_R_Corolla_red_seats_corolla_red_0.geometry} material={materials['glass_gauges.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Seats_R_Corolla_red_blue_seats_corolla_red_blue_0.geometry} material={materials['glass_gauges.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Seats_R_Corolla_red_purple_seats_corolla_red_purple_0.geometry} material={materials['glass_gauges.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Shifter_Corolla_buttons_0.geometry} material={materials.buttons} />
            <mesh geometry={nodes.Shifter_Corolla_leather_corolla_0.geometry} material={materials['trunk.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Shifter_Corolla2_plastic_corolla_0.geometry} material={materials['plastic_corolla.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Shifter_Corolla_auto_at_0.geometry} material={materials['glass_gauges.001']} />
            <mesh geometry={nodes.Shifter_Corolla_auto_rubber_0.geometry} material={materials['rubber.001']} />
          </group>
          <group position={[3.23, 47.52, 27.71]} rotation={[-1.66, 0, 0]} scale={100}>
            <mesh geometry={nodes.Shifter_Corolla_auto2_at_0.geometry} material={materials['glass_gauges.001']} />
            <mesh geometry={nodes.Shifter_Corolla_auto2_chrome_0.geometry} material={materials['chrome.001']} />
            <mesh geometry={nodes.Shifter_Corolla_auto2_plastic_corolla2_0.geometry} material={materials['plastic_corolla2.001']} />
            <mesh geometry={nodes.Shifter_Corolla_auto2_rubber_0.geometry} material={materials['rubber.001']} />
          </group>
          <group position={[-38.77, 77.83, 39.65]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.signal_buttons_0.geometry} material={materials.buttons} />
          </group>
          <group position={[-38.77, 77.83, 39.65]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.signalstalk_Corolla_rest_0.geometry} material={materials['Material.003']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Staby_Corolla_underchassis_corolla_0.geometry} material={materials.trunk} />
          </group>
          <group position={[-31.8, 77.64, 38.26]} rotation={[-2.79, 0, 0]} scale={101.64}>
            <mesh geometry={nodes.Steeringwheeba_leather_corolla_0.geometry} material={materials['trunk.001']} />
          </group>
          <group position={[-31.63, 76.71, 39.62]} rotation={[-2.79, 0, 0]} scale={100}>
            <mesh geometry={nodes.Steeringwheel_Corolla_buttons_0.geometry} material={materials.buttons} />
            <mesh geometry={nodes.Steeringwheel_Corolla_leather_corolla_0.geometry} material={materials['trunk.001']} />
            <mesh geometry={nodes.Steeringwheel_Corolla_steel_corolla_0.geometry} material={materials['glass_gauges.001']} />
          </group>
          <group position={[-31.63, 76.71, 39.62]} rotation={[-2.79, 0, 0]} scale={100}>
            <mesh geometry={nodes.Steeringwheel_Corolla_bl_leather_corolla_0.geometry} material={materials['trunk.001']} />
            <mesh geometry={nodes.Steeringwheel_Corolla_bl_steel_corolla_0.geometry} material={materials['glass_gauges.001']} />
            <mesh geometry={nodes.Steeringwheel_Corolla_bl_tc16_0.geometry} material={materials['trunk.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Swaybar_Corolla_engine_corolla_0.geometry} material={materials['engine_corolla.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Swaybar_Corolla_001_engine_corolla_0.geometry} material={materials['engine_corolla.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Taillight_RL_Corollaa_chrome2_0.geometry} material={materials.glass_gauges} />
            <mesh geometry={nodes.Taillight_RL_Corollaa_plastic_corolla2_0.geometry} material={materials.plastic_corolla2} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Taillight_RR_Corolla_chrome_0.geometry} material={materials.chrome} />
            <mesh geometry={nodes.Taillight_RR_Corolla_plastic_corolla2_0.geometry} material={materials.plastic_corolla2} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Taillightglass_RL_Corolla_old_corolla_reverselight_r_old_0.geometry} material={materials.TireMaterial} />
            <mesh geometry={nodes.Taillightglass_RL_Corolla_old_corolla_signal_l_old_0.geometry} material={materials.corolla_signal_l_old} />
            <mesh geometry={nodes.Taillightglass_RL_Corolla_old_corolla_taillight_r_old_0.geometry} material={materials.corolla_taillight_r_old} />
            <mesh geometry={nodes.Taillightglass_RL_Corolla_old_corolla_taillight_r_old_brake_0.geometry} material={materials.corolla_taillight_r_old_brake} />
            <mesh geometry={nodes.Taillightglass_RL_Corolla_old_Zenkilights_0.geometry} material={materials.Zenkilights} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Taillightglass_RL_Corolla_old2_strip_early_0.geometry} material={materials.glass_gauges} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Taillightglass_RR_Corolla_old_corolla_reverselight_r_old_0.geometry} material={materials.TireMaterial} />
            <mesh geometry={nodes.Taillightglass_RR_Corolla_old_corolla_signal_r_old_0.geometry} material={materials.corolla_signal_r_old} />
            <mesh geometry={nodes.Taillightglass_RR_Corolla_old_corolla_taillight_r_old_0.geometry} material={materials.corolla_taillight_r_old} />
            <mesh geometry={nodes.Taillightglass_RR_Corolla_old_corolla_taillight_r_old_brake_0.geometry} material={materials.corolla_taillight_r_old_brake} />
            <mesh geometry={nodes.Taillightglass_RR_Corolla_old_Zenkilights_0.geometry} material={materials.Zenkilights} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Taillightglass_RR_Corolla_old2_strip_early_0.geometry} material={materials.glass_gauges} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Tierod_Corolla_engine_corolla_0.geometry} material={materials['engine_corolla.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.tofubox_common_mirror_generic_0.geometry} material={materials.common_mirror_generic} />
            <mesh geometry={nodes.tofubox_vehicle_generic_smallspecmap_generic_0.geometry} material={materials.vehicle_generic_smallspecmap_generic} />
            <mesh geometry={nodes.tofubox_wood_generic_0.geometry} material={materials.wood_generic} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Toyota_4A__117_color_0.geometry} material={materials.color} />
            <mesh geometry={nodes.Toyota_4A__117_engine_wires_0.geometry} material={materials.engine_wires} />
            <mesh geometry={nodes.Toyota_4A__117_plastic_corolla_0.geometry} material={materials.plastic_corolla} />
            <mesh geometry={nodes.Toyota_4A__117_rubber_0.geometry} material={materials.rubber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.TransmissionConnection_Corolla_engine_corolla2_0.geometry} material={materials.trunk} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Trash_Corolla_Aluminum_black_0.geometry} material={materials.Aluminum_black} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Trunk_Corolla_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.Trunk_Corolla_chrome_0.geometry} material={materials.chrome} />
            <mesh geometry={nodes.Trunk_Corolla_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
            <mesh geometry={nodes.Trunk_Corolla_plastic_corolla_0.geometry} material={materials.plastic_corolla} />
            <mesh geometry={nodes.Trunk_Corolla_rubber_0.geometry} material={materials.rubber} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Underchassis_Corolla_test_etki_0.geometry} material={materials.etki} />
            <mesh geometry={nodes.Underchassis_Corolla_test_hatch_0.geometry} material={materials.glass_gauges} />
            <mesh geometry={nodes.Underchassis_Corolla_test_Matte__FFFFFFFF__prim_env_12_spec__0.geometry} material={materials.Matte__FFFFFFFF__prim_env_12_spec} />
            <mesh geometry={nodes.Underchassis_Corolla_test_plastic_corolla_0.geometry} material={materials.plastic_corolla} />
            <mesh geometry={nodes.Underchassis_Corolla_test_rubber_0.geometry} material={materials.rubber} />
            <mesh geometry={nodes.Underchassis_Corolla_test_underchassis_corolla_0.geometry} material={materials.trunk} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.warninglights_checkengine_0.geometry} material={materials['glass_gauges.001']} />
            <mesh geometry={nodes.warninglights_lowpressure_0.geometry} material={materials.lowpressure} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.wetten_leuchte_0.geometry} material={materials.leuchte} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.wetten2_leuchte_bl_0.geometry} material={materials.leuchte_bl} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Windscreen_Corolla_int_glass_corolla_int_0.geometry} material={materials.glass_corolla_int} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scuffed_ae86.glb')
